export const READ_COMMUNITIES_REQUEST = "READ_COMMUNITIES_REQUEST";
export const READ_COMMUNITIES_SUCCESS = "READ_COMMUNITIES_SUCCESS";
export const READ_COMMUNITIES_FAILURE = "READ_COMMUNITIES_FAILURE";
export const JOIN_COMMUNITY_REQUEST = "JOIN_COMMUNITY_REQUEST";
export const JOIN_COMMUNITY_SUCCESS = "JOIN_COMMUNITY_SUCCESS";
export const JOIN_COMMUNITY_FAILURE = "JOIN_COMMUNITY_FAILURE";
