export const READ_COMMUNITIES_REQUEST = "READ_COMMUNITIES_REQUEST";
export const READ_COMMUNITIES_SUCCESS = "READ_COMMUNITIES_SUCCESS";
export const READ_COMMUNITIES_FAILURE = "READ_COMMUNITIES_FAILURE";
