export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";
export const READ_POSTS_REQUEST = "READ_POSTS_REQUEST";
export const READ_POSTS_SUCCESS = "READ_POSTS_SUCCESS";
export const READ_POSTS_FAILURE = "READ_POSTS_FAILURE";
