export const VOTE_COMMENT_REQUEST = "VOTE_COMMENT_REQUEST";
export const VOTE_COMMENT_SUCCESS = "VOTE_COMMENT_SUCCESS";
export const VOTE_COMMENT_FAILURE = "VOTE_COMMENT_FAILURE";
export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";
